[tools]
node = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
python = "latest"
rust = "latest"
go = "latest"
lazygit = "latest"
"npm:vercel" = "latest"
"npm:opencode-ai" = "latest"
"npm:vibe-kanban" = "latest"
"npm:openai/codex" = "latest"
bun = "latest"
codex = "latest"

[settings]
experimental = true
not_found_auto_install = false
